TG_TOKEN="6873341222:AAFnVgfavenjwbKutRwROQQBya_XXXXXXXX"
TG_CHAT="8888888888,999999999"
PROXY="True"
PROXY_ADDR="http://192.168.3.100:9090"
PROXY_USER="LOGIN"
PROXY_PASS="PASSWORD"
KZ_ADDR="https://kinozal.tv"
KZ_USER="LOGIN"
KZ_PASS="PASSWORD"
KZ_PROFILE="20631917"
QB_ADDR="http://192.168.3.100:8888"
QB_USER="LOGIN"
QB_PASS="PASSWORD"
TRANS_ADDR="http://192.168.3.100:9091"
TRANS_USER="LOGIN"
TRANS_PASS="PASSWORD"
PLEX_ADDR="http://192.168.3.100:32400"
PLEX_TOKEN="XXXXXXXXXXXXXXXXXXXX"
KINOBOX_PLAYERS="False"
KINOPOISK_API="True"
KINOPOISK_TOKEN="XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX"
DATA_TIMEZONE="+3"
path="/home/lifailon/kinozal-bot"
log_size_mbyte=10
TG_CHANNEL="-1002064864175"
RATING_KP=7
RATING_IMDB=7
FILTER_YEAR=2023
TIMEOUT_SEC_POST=300
TIMEOUT_SEC_ERROR=60
TIMEOUT_SEC_UPDATE_STATUS=1